export const SET_BITES = 'SET_BITES'
export const SET_BITE = 'SET_BITE'
export const ADD_BITE = 'ADD_BITE'
export const LIKE_BITE = 'LIKE_BITE'
export const UNLIKE_BITE = 'UNLIKE_BITE'
export const COMMENT_BITE = 'COMMENT_BITE'
export const DELETE_BITE = 'DELETE_BITE'
export const LOADING_BITES = 'LOADING_BITES'
