export const SET_AUTHENTICATED = 'SET_AUTHENTICATED'
export const SET_AUTHENTICATED_PROFILE = 'SET_AUTHENTICATED_PROFILE'
export const LOGOUT = 'LOGOUT'
export const LOADING_PROFILE = 'LOADING_PROFILE'